server {
  listen 80;
  server_name _;
  root /usr/share/nginx/html;
  index index.html;

  location ~* \.(?:css|js|mjs|map|json|png|jpe?g|gif|svg|ico|webp|woff2?|ttf|eot)$ {
    try_files $uri =404;
  }

  location / {
    try_files $uri $uri/ /index.html;
  }
}
